### PR TITLE
fixes #19

### LINKED ISSUE #19: ukuu shows no internet connection
ukuu always shows no internet connection dialog box but can get all the new kernels.When installing the same no internet connection error occurs

### PR DESCRIPTION
**Pull request by tristanrobert**
Hello,

When ping command is not allowed (e.g behind an enterprise proxy), your Internet connection test never succeeds. So I suggest this pull request, I replace ping command by a curl command to test connection. Now it works fine. It fixes #19

### CODE REVIEW

**Comment by Bavarianph** [comment]
ukuu bug fix # 19 cannot be compiled.
Can you please update ukuu ppa or deb file with curl enabled

**Comment by tristanrobert** [comment]
I reverted `ukku.pot`. It was not necessary in the pull request. Only `src/Utility/TeeJee.System.vala` has changed.

**Comment by teejee2008** [comment]
Thanks

**Comment by Bavarianph** [comment]
ukuu-5be9a9aa1852d3c3889a84fed618d4ebbe94f6ff
successful, compiled, installed and working great.
Thank you very much.
BavarianPH

**Pull request merged**
